# tenforflow 入门教学

In [2]:
import tensorflow as tf
message = tf.constant('Welcome to the exciting world of Deep Neural Networks!')
with tf.Session() as sess:
    print(sess.run(message).decode())
sess = tf.Session()

/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or 

Welcome to the exciting world of Deep Neural Networks!


In [2]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
with tf.Session() as sess:
    print(sess.run(v_1))
    print(sess.run(v_2))
    print(sess.run(v_add))
    print(sess.run(tf.add(tf.constant([1,2,3,4]),tf.constant([2,1,5,3]))))

[1 2 3 4]
[2 1 5 3]
[3 3 8 7]
[3 3 8 7]


In [3]:
sess2 = tf.InteractiveSession()
print(sess2.run(v_add))
print(v_add.eval())
sess2.close()

[3 3 8 7]
[3 3 8 7]


## 要创建一个所有元素为零的张量，可以使用 tf.zeros() 函数。这个语句可以创建一个形如 [M，N] 的零元素矩阵，数据类型（dtype）可以是 int32、float32 等：

In [7]:
zero_t = tf.zeros([3,4],tf.int32)
sess.run(zero_t)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

## 创建一个所有元素都设为 1 的张量。下面的语句即创建一个形如 [M，N]、元素均为 1 的矩阵：

In [ ]:
ones_t = tf.ones([2,3],tf.int32)
sess.run(ones_t)

## 在一定范围内生成一个从初值到终值等差排布的序列

In [ ]:
range_t = tf.linspace(2.0,15.0,5)
sess.run(range_t)

## 从开始（默认值=0）生成一个数字序列，增量为 delta（默认值=1），直到终值（但不包括终值）

In [ ]:
range_t = tf.range(10)
sess.run(range_t)

## 使用以下语句创建一个具有一定均值（默认值=0.0）和标准差（默认值=1.0）、形状为 [M，N] 的正态分布随机数组

In [8]:
t_random = tf.random_normal([2,3], mean=12.0, stddev=100 , seed=12)
sess.run(t_random)

array([[-31.663136 ,  96.49774  ,  10.819015 ],
       [-76.44008  ,  -6.5275383,  33.195168 ]], dtype=float32)

![chicken.png](./images/chicken.jpg)

In [9]:
#很多时候需要以随机的顺序来呈现训练样本，可以使用 tf.random_shuffle() 来沿着它的第一维随机排列张量。如果 t_random 是想要重新排序的张量，使用下面的代码：
t_random_shuffle = tf.random_shuffle(t_random)
sess.run(t_random_shuffle)

array([[ 151.85995 ,  -17.988905,   79.422134],
       [-146.7453  , -115.33358 ,  168.8891  ]], dtype=float32)

In [ ]:
sess.run(t_random)

In [ ]:
## TensorFlow 变量

In [14]:
rand_t = tf.random_uniform([50,50], 0,10,seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t)
sess.run(rand_t)
sess.run(t_a)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

In [17]:
!ls -alh

total 64K
drwxr-xr-x.  4 root root   94 2月  16 19:26 .
dr-xr-x---. 28 root root 4.0K 2月  16 17:33 ..
-rw-r--r--.  1 root root  38K 2月  16 17:31 a.ipynb
drwxr-xr-x.  2 root root   25 2月  16 19:09 images
drwxr-xr-x.  2 root root   76 2月  16 17:44 .ipynb_checkpoints
-rw-r--r--.  1 root root  18K 2月  16 19:26 tensorflow_tutorial.ipynb
