# tenforflow 入门教学

In [1]:
import tensorflow as tf

In [2]:
message = tf.constant('Welcome to the exciting world of Deep Neural Networks!')
with tf.Session() as sess:
    print(sess.run(message).decode())

Welcome to the exciting world of Deep Neural Networks!


In [3]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
with tf.Session() as sess:
    print(sess.run(v_1))
    print(sess.run(v_2))
    print(sess.run(v_add))
    print(sess.run(tf.add(tf.constant([1,2,3,4]),tf.constant([2,1,5,3]))))

[1 2 3 4]
[2 1 5 3]
[3 3 8 7]
[3 3 8 7]


In [4]:
sess2 = tf.InteractiveSession()
print(sess2.run(v_add))
print(v_add.eval())
sess2.close()

[3 3 8 7]
[3 3 8 7]


## 要创建一个所有元素为零的张量，可以使用 tf.zeros() 函数。这个语句可以创建一个形如 [M，N] 的零元素矩阵，数据类型（dtype）可以是 int32、float32 等：

In [5]:
zero_t = tf.zeros([3,4],tf.int32)
with tf.Session() as sess:
    sess.run(zero_t)

## 创建一个所有元素都设为 1 的张量。下面的语句即创建一个形如 [M，N]、元素均为 1 的矩阵：

In [6]:
ones_t = tf.ones([2,3],tf.int32)
with tf.Session() as sess:
    sess.run(ones_t)

## 在一定范围内生成一个从初值到终值等差排布的序列

In [7]:
range_t = tf.linspace(2.0,15.0,5)
with tf.Session() as sess:
    sess.run(range_t)

## 从开始（默认值=0）生成一个数字序列，增量为 delta（默认值=1），直到终值（但不包括终值）

In [8]:
range_t = tf.range(10)
with tf.Session() as sess:
    sess.run(range_t)

## 使用以下语句创建一个具有一定均值（默认值=0.0）和标准差（默认值=1.0）、形状为 [M，N] 的正态分布随机数组

In [9]:
t_random = tf.random_normal([2,3], mean=12.0, stddev=100 , seed=12)
with tf.Session() as sess:
    sess.run(t_random)

![chicken.png](./images/chicken.jpg)

In [10]:
#很多时候需要以随机的顺序来呈现训练样本，可以使用 tf.random_shuffle() 来沿着它的第一维随机排列张量。如果 t_random 是想要重新排序的张量，使用下面的代码：
t_random_shuffle = tf.random_shuffle(t_random)
sess.run(t_random_shuffle)

RuntimeError: Attempted to use a closed Session.

In [ ]:
sess.run(t_random)

In [ ]:
## TensorFlow 变量

In [ ]:
rand_t = tf.random_uniform([50,50], 0,10,seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t)
sess.run(rand_t)

## 下面的代码中定义了两个变量的权重和偏置。权重变量使用正态分布随机初始化，均值为 0，标准差为 2，权重大小为 100×100。偏置由 100 个元素组成，每个元素初始化为 0。在这里也使用了可选参数名以给计算图中定义的变量命名：

In [ ]:
weights = tf.Variable(tf.random_normal([100,100], stddev=2),name="w1")
bias = tf.Variable(tf.zeros([100]), name='biases')

## 在前面的例子中，都是利用一些常量来初始化变量，也可以指定一个变量来初始化另一个变量。下面的语句将利用前面定义的权重来初始化 weight2

In [ ]:
weights2 = tf.Variable(weights.initialized_value(), name="w2")

In [ ]:
#初始化变量
intial_op = tf.global_variables_initializer()
#单独初始化
sess.run(bias.initializer)


## 保存变量：使用 Saver 类来保存变量，定义一个 Saver 操作对象：

In [ ]:
saver = tf.train.Saver()

## 最重要的元素——占位符，它们用于将数据提供给计算图。可以使用以下方法定义一个占位符：

In [ ]:
x = tf.placeholder("float", name="xxx")
y = 12 * x
data = tf.random_uniform([4,5],10)
with tf.Session() as sess:
    x_data = sess.run(data)
    print(sess.run(y, feed_dict={x:x_data}))

In [ ]:
with tf.Session() as sess:
    for i in sess.run(tf.range(10)):
        print(i)