In [23]:
import tensorflow as tf

In [24]:
sess = tf.InteractiveSession()
I_matrix = tf.eye(5)
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
X = tf.Variable(tf.eye(10))
X.initializer.run()
print(X.eval())

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [26]:
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()
product = tf.matmul(A,X)
print(product.eval())

[[-1.4425962  -1.479247   -1.0865619  -0.3306201  -0.69811255 -0.9433381
  -0.32645872  1.0110965  -0.9433155   0.70876265]
 [ 0.85513824 -1.0758579   1.0953991   1.3307794   1.8043773   0.08736993
   1.1555424   0.15194623 -0.5848845   0.05621802]
 [ 1.893398    1.0295573  -0.23870654 -0.381546   -1.5832938  -0.00324788
   0.5930881   1.7196118  -1.3704036  -0.70710105]
 [ 0.31799072 -0.6157135   0.46539345 -0.02777515  0.7907513  -0.4561105
  -0.27855703  0.49408376  0.8100402  -0.525993  ]
 [-0.16027822  0.78828084 -1.3840497   2.2986681   0.22530581 -1.3530664
   0.8964613  -0.6975697  -0.3581016  -0.02974967]]


In [27]:
b = tf.Variable(tf.random_uniform([5,10],0,2,dtype=tf.int32))
b.initializer.run()
print(b.eval())
b_new = tf.cast(b, dtype=tf.float32)
print(b_new.eval())

[[1 1 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 1 0 0 1 0]
 [0 0 1 0 0 0 0 1 1 0]
 [1 0 0 1 1 1 1 0 1 1]
 [0 1 1 0 0 1 1 0 1 0]]
[[1. 1. 0. 0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 0. 1. 1. 0. 1. 0.]]


In [28]:
t_sum = tf.add(product, b_new)
t_sub = product - b_new

print("A*X + b\n", t_sum.eval())
print("A*x - b\n", t_sub.eval())

A*X + b
 [[-0.4425962  -0.47924697 -1.0865619  -0.3306201  -0.69811255 -0.9433381
   0.6735413   1.0110965   0.05668449  1.7087626 ]
 [ 0.85513824 -1.0758579   1.0953991   1.3307794   1.8043773   1.0873699
   1.1555424   0.15194623  0.41511548  0.05621802]
 [ 1.893398    1.0295573   0.7612935  -0.381546   -1.5832938  -0.00324788
   0.5930881   2.7196116  -0.37040365 -0.70710105]
 [ 1.3179908  -0.6157135   0.46539345  0.97222483  1.7907512   0.5438895
   0.72144294  0.49408376  1.8100402   0.474007  ]
 [-0.16027822  1.7882808  -0.38404965  2.2986681   0.22530581 -0.35306644
   1.8964612  -0.6975697   0.6418984  -0.02974967]]
A*x - b
 [[-2.4425962  -2.479247   -1.0865619  -0.3306201  -0.69811255 -0.9433381
  -1.3264587   1.0110965  -1.9433155  -0.29123735]
 [ 0.85513824 -1.0758579   1.0953991   1.3307794   1.8043773  -0.9126301
   1.1555424   0.15194623 -1.5848845   0.05621802]
 [ 1.893398    1.0295573  -1.2387066  -0.381546   -1.5832938  -0.00324788
   0.5930881   0.71961176 -2.3704038 

In [37]:
a = tf.Variable(tf.random_normal([4,5], stddev=2))
b = tf.Variable(tf.random_normal([4,5], stddev=2))
A = a*b
B = tf.scalar_mul(2,A)
C = tf.truediv(a,b)
D = tf.mod(a,b)

init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)    
    a,b,A_R,B_R,C_R,D_R = sess.run([a,b,A,B,C,D])
    print("a\n",a,"\nb\n",b,"\na*b\n",A_R,"\n2*a*b",B_R,"\na/b\n",C_R,"\na%b\n",D_R)
    writer = tf.summary.FileWriter('graph', sess.graph)



a
 [[ 1.3672756  -1.3302102   1.5509079  -0.12154876  0.10123684]
 [ 1.1369488   1.2137512  -0.46539772 -2.2217026  -4.470971  ]
 [ 1.3688327   3.92448     2.0883758  -0.25126803 -2.5847754 ]
 [ 2.7139308  -1.2063186  -1.3134795   1.3927776  -2.4455185 ]] 
b
 [[ 2.9503639   1.9037814  -3.4279618   0.49910685  1.574336  ]
 [-1.9260086   2.6897352   1.4610746  -2.2013733  -0.8139096 ]
 [-1.5483799  -1.9211113  -2.9094114  -0.19413276  0.15257548]
 [ 2.7759938   1.9254074  -1.678204   -1.8411264  -1.176998  ]] 
a*b
 [[ 4.0339603  -2.5324295  -5.316453   -0.06066582  0.15938081]
 [-2.189773    3.2646692  -0.67998075  4.8907967   3.6389663 ]
 [-2.119473   -7.539363   -6.0759444   0.04877936 -0.39437336]
 [ 7.5338554  -2.3226547   2.2042868  -2.5642796   2.8783705 ]] 
2*a*b [[  8.067921    -5.064859   -10.632906    -0.12133163   0.31876162]
 [ -4.379546     6.5293384   -1.3599615    9.781593     7.2779326 ]
 [ -4.238946   -15.078726   -12.151889     0.09755871  -0.7887467 ]
 [ 15.067711    -